### ISSUE TITLE
What's a Zing

### ISSUE THREAD

**Issue by kragniz** [HewlettPackard/windlass#9]

**Comment by electrofelix** [comment]
It was the name given to an internal CI infrastructure that is being shut down, however figured that some of the tools developed might be useful in the future and elsewhere

**Comment by kragniz** [comment]
rip zing

**Comment by kragniz** [comment]
How did you edit the git history to replace the project name everywhere? (like in https://github.com/HewlettPackard/windlass/commit/9adbaae8742094646d98a51d59eecbc27dffb554)

**Comment by mulcahys** [comment]
also, Zing Is Not Gozer

**Comment by kragniz** [comment]
What's a Gozer

**Comment by mulcahys** [comment]
According to popular culture, an antagonist

**Comment by electrofelix** [comment]
@kragniz `git filter-branch` magic, somewhat of a requirement to strip most internal references with the exception of the name `zing` as that was already referenced in another project that had already been published.

The alternative was to squish the history and mask other peoples contributions, in addition to removing information on why some changes were made. As it only took about 2-3 hrs to clean up anyway it seemed worthwhile to be able to look back when making subsequent changes.

**Comment by kragniz** [comment]
nice :ok_hand:
